# Default settings
# controllers:
#     resource: ../../src/Controller/
#     type: annotation

# This could be useful if using rest API
# web_controller:
#    resource: ../../src/Controller/Web/
#    type: annotation

rest_controller:
    resource: ../../src/Controller/Rest/
    type: annotation
    prefix: /api

#controllers:
#    resource: ../../src/Controller/
#    type: annotation
